version: '3.9'
services:
  frontend:
    env_file:
      - ./App/frontend/.env.local
    container_name: frontend
    build: ./App/frontend
    networks:
      - frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/frontend/src
    platform: linux/x86_64
    working_dir: /frontend
    command: npm start
    depends_on:
      api:
        condition: service_healthy
    # Os `healthcheck` devem garantir que a aplicação
    # está operacional, antes de liberar o container
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]  # Caso utilize outra porta interna para o front, altere ela aqui também
      timeout: 10s
      retries: 5
      security:
        condition: service_healthy
  api:
    env_file:
      - ./App/backend/api/.env.local
    container_name: backend
    build: ./App/backend/api
    networks:
      - frontend
      - database
      -	security
    ports:
      - 3001:3001
    volumes:
      - ./backend/api
    platform: linux/x86_64
    working_dir: /backend/api
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      # Os dados abaixo se referem ao container `db`
      # Dica: Relembre aqui da comunicação interna entre containers
      - DB_USER=root
      - DB_PASS=#INSERIR SENHA DO BANCO
      - DB_HOST=db
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5
  security:
      env_file:
        - ./App/backend/security/.env.local
      container_name: security
      build: ./App/backend/security
      networks:
        - frontend
        - database
        -	api
      ports:
        - 3002:3002
      volumes:
        - ./backend/security
      platform: linux/x86_64
      working_dir: /backend/security
      command: npm run dev
      depends_on:
        db:
          condition: service_healthy
      environment:
        - APP_PORT=3002
        - JWT_SECRET=jwt_secret
        # Os dados abaixo se referem ao container `db`
        # Dica: Relembre aqui da comunicação interna entre containers
        - DB_USER=root
        - DB_PASS=#INSERIR SENHA DO BANCO
        - DB_HOST=db
        - DB_PORT=3306
      healthcheck:
        test: ["CMD", "lsof", "-t", "-i:3001"] # Caso utilize outra porta interna para o back, altere ela aqui também
        timeout: 10s
        retries: 5
  db:
    image: mysql:5.7
    container_name: database
    networks:
      - database
    platform: linux/x86_64
    ports:
      - 3002:3306
    volumes:
      - ./src:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=#INSERIR NOME DO BANCO
      - MYSQL_ROOT_PASSWORD=#INSERIR SENHA DO BANCO
      - TZ=America/Sao_Paulo
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=-03:00', '--skip-character-set-client-handshake']
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
networks:
  frontend:
  database:
  api:
  backend: